export const entryColumns = [
  {
    title: "ITEM",
    dataIndex: "item",
    key: "item",
    className: "text-center",
    width: 200,
  },
  {
    title: "FECHA DE RADICADO",
    dataIndex: "radicateDate",
    key: "radicateDate",
    className: "text-center",
    width: 200,
  },
  {
    title: "HORA DE RADICADO",
    dataIndex: "radicateHour",
    key: "radicateHour",
    className: "text-center",
    width: 100,
  },
  {
    title: "MES DE RADICADO",
    dataIndex: "radicateMonth",
    key: "radicateMonth",
    className: "text-center",
    width: 150,
  },
  {
    title: "DÍAS DE VENCIMIENTO",
    dataIndex: "expirationDays",
    key: "expirationDays",
    className: "text-center",
    width: 100,
  },
  {
    title: "FECHA MÁXIMA DE RESPUESTA",
    dataIndex: "deadlineForResponse",
    key: "deadlineForResponse",
    className: "text-center",
    width: 200,
  },
  {
    title: "RADICADO",
    dataIndex: "numberEntryClaim",
    key: "numberEntryClaim",
    className: "text-center",
    width: 200,
  },
  {
    title: "NOMBRE DEL REMITENTE",
    dataIndex: "name",
    key: "name",
    className: "text-center",
    width: 200,
  },
  {
    title: "TIPO DE DOCUMENTO",
    dataIndex: "documentType",
    key: "documentType",
    className: "text-center",
    width: 100,
  },
  {
    title: "IDENTIFICACIÓN",
    dataIndex: "documentNumber",
    key: "documentNumber",
    className: "text-center",
    width: 200,
  },
  {
    title: "ASIGNADO A",
    dataIndex: "assignedTo",
    key: "assignedTo",
    className: "text-center",
    width: 200,
  },
  {
    title: "ESTADO",
    dataIndex: "status",
    key: "status",
    className: "text-center",
    width: 150,
  },
  {
    title: "OBSERVACIÓN",
    dataIndex: "observations",
    key: "observations",
    className: "text-center",
    width: 200,
  },
  {
    title: "RADICADO RESPUESTA",
    dataIndex: "numberOutClaim",
    key: "numberOutClaim",
    className: "text-center",
    width: 200,
  },
  {
    title: "MEDIO SALIDA",
    dataIndex: "outputMedium",
    key: "outputMedium",
    className: "text-center",
    width: 200,
  },
];

export const departureColumns = [
  {
    title: "ITEM",
    dataIndex: "item",
    key: "item",
    className: "text-center",
    width: 200,
  },
  {
    title: "RADICADO",
    dataIndex: "numberOutClaim",
    key: "numberOutClaim",
    className: "text-center",
    width: 200,
  },
  {
    title: "FECHA DE RADICADO",
    dataIndex: "radicateDate",
    key: "radicateDate",
    className: "text-center",
    width: 200,
  },
  {
    title: "HORA DE RADICADO",
    dataIndex: "radicateHour",
    key: "radicateHour",
    className: "text-center",
    width: 100,
  },
  {
    title: "MES DE RADICADO",
    dataIndex: "radicateMonth",
    key: "radicateMonth",
    className: "text-center",
    width: 150,
  },
  {
    title: "TIPO DE DOCUMENTO",
    dataIndex: "documentType",
    key: "documentType",
    className: "text-center",
    width: 100,
  },
  {
    title: "NÚMERO IDENTIFICACIÓN",
    dataIndex: "documentNumber",
    key: "documentNumber",
    className: "text-center",
    width: 200,
  },
  {
    title: "NOMBRE DESTINATARIO",
    dataIndex: "destinationName",
    key: "destinationName",
    className: "text-center",
    width: 200,
  },
  {
    title: "MEDIO SALIDA",
    dataIndex: "outputMedium",
    key: "outputMedium",
    className: "text-center",
    width: 200,
  },
  {
    title: "ÁREA",
    dataIndex: "area",
    key: "area",
    className: "text-center",
    width: 200,
  },
  {
    title: "RESPONDIDO POR",
    dataIndex: "answeredBy",
    key: "answeredBy",
    className: "text-center",
    width: 200,
  },
  {
    title: "OBSERVACIÓN",
    dataIndex: "observations",
    key: "observations",
    className: "text-center",
    width: 200,
  },
  {
    title: "RADICADO ENTRADA",
    dataIndex: "numberEntryClaim",
    key: "numberEntryClaim",
    className: "text-center",
    width: 200,
  },
];

export const pendingColumns = [
  {
    title: "ITEM",
    dataIndex: "item",
    key: "item",
    className: "text-center",
    width: 200,
  },
  {
    title: "RADICADO DE ENTRADA",
    dataIndex: "numberEntryClaim",
    key: "numberEntryClaim",
    className: "text-center",
    width: 200,
  },
  {
    title: "FECHA DE RADICADO",
    dataIndex: "radicateDate",
    key: "radicateDate",
    className: "text-center",
    width: 200,
  },
  {
    title: "HORA DE RADICADO",
    dataIndex: "radicateHour",
    key: "radicateHour",
    className: "text-center",
    width: 100,
  },
  {
    title: "MES DE RADICADO",
    dataIndex: "radicateMonth",
    key: "radicateMonth",
    className: "text-center",
    width: 150,
  },
  {
    title: "DÍAS DE VENCIMIENTO",
    dataIndex: "expirationDays",
    key: "expirationDays",
    className: "text-center",
    width: 100,
  },
  {
    title: "FECHA MÁXIMA DE RESPUESTA",
    dataIndex: "deadlineForResponse",
    key: "deadlineForResponse",
    className: "text-center",
    width: 200,
  },
  {
    title: "RADICADO",
    dataIndex: "numberOutClaim",
    key: "numberOutClaim",
    className: "text-center",
    width: 200,
  },
  {
    title: "NOMBRE DEL REMITENTE",
    dataIndex: "destinationName",
    key: "destinationName",
    className: "text-center",
    width: 200,
  },
  {
    title: "TIPO DE DOCUMENTO",
    dataIndex: "documentType",
    key: "documentType",
    className: "text-center",
    width: 100,
  },
  {
    title: "IDENTIFICACIÓN",
    dataIndex: "documentNumber",
    key: "documentNumber",
    className: "text-center",
    width: 200,
  },
  {
    title: "ASIGNADO A",
    dataIndex: "assignedTo",
    key: "assignedTo",
    className: "text-center",
    width: 200,
  },
  {
    title: "ESTADO",
    dataIndex: "status",
    key: "status",
    className: "text-center",
    width: 200,
  },
];
