export const entryColumns = [
  {
    title: "Item",
    dataIndex: "item",
    key: "item",
    className: "text-center",
    width: 200,
  },
  {
    title: "Fecha de Radicado",
    dataIndex: "radicateDate",
    key: "radicateDate",
    className: "text-center",
    width: 200,
  },
  {
    title: "Hora de Radicado",
    dataIndex: "radicateHour",
    key: "radicateHour",
    className: "text-center",
    width: 100,
  },
  {
    title: "Mes de Radicado",
    dataIndex: "radicateMonth",
    key: "radicateMonth",
    className: "text-center",
    width: 150,
  },
  {
    title: "Días de Vencimiento",
    dataIndex: "expirationDays",
    key: "expirationDays",
    className: "text-center",
    width: 100,
  },
  {
    title: "Fecha Maxima de Respuesta",
    dataIndex: "deadlineForResponse",
    key: "deadlineForResponse",
    className: "text-center",
    width: 200,
  },
  {
    title: "Radicado",
    dataIndex: "numberEntryClaim",
    key: "numberEntryClaim",
    className: "text-center",
    width: 200,
  },
  {
    title: "Nombre del Remitente",
    dataIndex: "name",
    key: "name",
    className: "text-center",
    width: 200,
  },
  {
    title: "Tipo de Documento",
    dataIndex: "documentType",
    key: "documentType",
    className: "text-center",
    width: 100,
  },
  {
    title: "Identificación",
    dataIndex: "documentNumber",
    key: "documentNumber",
    className: "text-center",
    width: 200,
  },
  {
    title: "Asigando a",
    dataIndex: "assignedTo",
    key: "assignedTo",
    className: "text-center",
    width: 200,
  },
  {
    title: "Estado",
    dataIndex: "status",
    key: "status",
    className: "text-center",
    width: 150,
  },
  {
    title: "Observación",
    dataIndex: "observations",
    key: "observations",
    className: "text-center",
    width: 200,
  },
  {
    title: "Radicado Respuesta",
    dataIndex: "numberOutClaim",
    key: "numberOutClaim",
    className: "text-center",
    width: 200,
  },
  {
    title: "Medio Salida",
    dataIndex: "outputMedium",
    key: "outputMedium",
    className: "text-center",
    width: 200,
  },
];

export const departureColumns = [
  {
    title: "Item",
    dataIndex: "item",
    key: "item",
    className: "text-center",
    width: 200,
  },
  {
    title: "Radicado",
    dataIndex: "numberOutClaim",
    key: "numberOutClaim",
    className: "text-center",
    width: 200,
  },
  {
    title: "Fecha de Radicado",
    dataIndex: "radicateDate",
    key: "radicateDate",
    className: "text-center",
    width: 200,
  },
  {
    title: "Hora de Radicado",
    dataIndex: "radicateHour",
    key: "radicateHour",
    className: "text-center",
    width: 100,
  },
  {
    title: "Mes de Radicado",
    dataIndex: "radicateMonth",
    key: "radicateMonth",
    className: "text-center",
    width: 150,
  },
  {
    title: "Tipo de Documento",
    dataIndex: "documentType",
    key: "documentType",
    className: "text-center",
    width: 100,
  },
  {
    title: "Número Identificación",
    dataIndex: "documentNumber",
    key: "documentNumber",
    className: "text-center",
    width: 200,
  },
  {
    title: "Nombre Destinatario",
    dataIndex: "destinationName",
    key: "destinationName",
    className: "text-center",
    width: 200,
  },
  {
    title: "Medio Salida",
    dataIndex: "outputMedium",
    key: "outputMedium",
    className: "text-center",
    width: 200,
  },
  {
    title: "Área",
    dataIndex: "area",
    key: "area",
    className: "text-center",
    width: 200,
  },
  {
    title: "Respondido Por",
    dataIndex: "answeredBy",
    key: "answeredBy",
    className: "text-center",
    width: 200,
  },
  {
    title: "Observación",
    dataIndex: "observations",
    key: "observations",
    className: "text-center",
    width: 200,
  },
  {
    title: "Radicado Entrada",
    dataIndex: "numberEntryClaim",
    key: "numberEntryClaim",
    className: "text-center",
    width: 200,
  },
];

export const pendingColumns = [
  {
    title: "Item",
    dataIndex: "item",
    key: "item",
    className: "text-center",
    width: 200,
  },
  {
    title: "Radicado de Entrada",
    dataIndex: "numberEntryClaim",
    key: "numberEntryClaim",
    className: "text-center",
    width: 200,
  },
  {
    title: "Fecha de Radicado",
    dataIndex: "radicateDate",
    key: "radicateDate",
    className: "text-center",
    width: 200,
  },
  {
    title: "Hora de Radicado",
    dataIndex: "radicateHour",
    key: "radicateHour",
    className: "text-center",
    width: 100,
  },
  {
    title: "Mes de Radicado",
    dataIndex: "radicateMonth",
    key: "radicateMonth",
    className: "text-center",
    width: 150,
  },
  {
    title: "Días de Vencimiento",
    dataIndex: "expirationDays",
    key: "expirationDays",
    className: "text-center",
    width: 100,
  },
  {
    title: "Fecha Maxima de Respuesta",
    dataIndex: "deadlineForResponse",
    key: "deadlineForResponse",
    className: "text-center",
    width: 200,
  },
  {
    title: "Radicado",
    dataIndex: "numberOutClaim",
    key: "numberOutClaim",
    className: "text-center",
    width: 200,
  },
  {
    title: "Nombre del Remitente",
    dataIndex: "destinationName",
    key: "destinationName",
    className: "text-center",
    width: 200,
  },
  {
    title: "Tipo de Documento",
    dataIndex: "documentType",
    key: "documentType",
    className: "text-center",
    width: 100,
  },
  {
    title: "Identificación",
    dataIndex: "documentNumber",
    key: "documentNumber",
    className: "text-center",
    width: 200,
  },
  {
    title: "Asigando a",
    dataIndex: "assignedTo",
    key: "assignedTo",
    className: "text-center",
    width: 200
  },
  {
    title: "Estado",
    dataIndex: "status",
    key: "status",
    className: "text-center",
    width: 200,
  },
];
